### PR TITLE
Implement #91, Fix #88, Add instructions to README

### LINKED ISSUE #88: Clicks in CR column do not add monster to encounter

### PR DESCRIPTION
**Pull request by vincentscode**
Hi, as discussed in #91 I added a button to import the current combat configuration into Improved Initiative!
Along the way I also fixed #88 - it was caused by not adding a class to the cells in the column.
I also added some basic instructions for getting started to the README since I had to spend some time figuring all of that out myself.

### CODE REVIEW

**Comment by struandw** [comment]
Thanks. I’ll take a closer look in the morning.

I appreciate you writing up the README; I’ll add a few extra tips but that’s a great start. Don’t worry about the build failing; looks like that’s just the wrong dataset.

**Comment by vincentscode** [comment]
Thanks, I will look into writing tests for my service!
The existing tests probably don't like me changing the database query and including more fields but as far as I could tell this does not impact any actual code.

**Comment by vincentscode** [comment]
All tests & checks should be happy now!

**Comment by struandw** [comment]
Mate this is terrific, thank you! Merging now, I’ll deploy it in the next day or so (currently ill, so doing the bare minimum.)

**Comment by vincentscode** [comment]
Thanks for merging, get well soon!

**Pull request merged**
